### ISSUE TITLE
Add GHA for periodic link checking?

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/Sheffield_RCC_Docs#8]
See https://github.com/rcgsheffield/sheffield_hpc/blob/master/.github/workflows/link-check.yml and tox.ini in that repo.

**Comment by willfurnass** [comment]
Useful if have lots of links to Ronin blog and want periodically check they are valid.

**Comment by cs1jmc** [comment]
We have this in the workflows already, but I'm thinking it would be a good check to have in pull-requests and static workflows so that we don't end up commiting changes with broken links.

**Comment by willfurnass** [comment]
Ah, just seen that https://github.com/rcgsheffield/Sheffield_RCC_Docs/blob/main/.github/workflows/link-check.yml has been commited.

Yes, we want internal link checking with every PR (and get that for free by using Sphinx+tox+GHA) but external link checking for every PR would be costly in terms of time and could mean PRs are held up by 300/400 errors relating to external resources.

I suggest we close this?
